### ISSUE TITLE
Enable routerLink option to right-click open in new window

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2#415]
### Expected behavior

RouterLinks in Angular aren't treated like hrefs, so we take away the option for a user to right-click open a link in a a new tab/window.

### Actual behavior

If we use stacheRouterLink, or even routerLink, we don't give the user the option to open a link in a new tab/window if they don't want to leave the page they are on. For external links, we can change stacheRouterLink to hrefs, but that still doesn't solve the problem for routerLinks within a site. 

This has been requested by Kim Coughlin, Derek Nichols, and RoxAnna Fuquay. They noted they would like it for action buttons, in addition to links.

Items Requested to have option for open in new window/browser tab:
- `stacheRouterLink`
- Action buttons

We should also add a documentation best practice note to the Tutorial component, that we recommend users enable links to be opened in a new window from a tutorial. When someone is following a tutorial, it is recommended that they give users the option to open in a new window/tab so they don't lose their step in the process.

**Comment by Blackbaud-TimPepper** [comment]
Users should now be able to use the StacheRouterLink with as much functionality as RouterLink, and then some. StacheRouterLink should now be used primarily, instead of RouterLink. 

Functionality includes: ctrl/shift/cmd(meta) + click navigation, and browser right-click context menu options, which were missing previously with StacheRouterLink.
